sudo: false

language: php
 
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

before_script:
  - export DEV_LIB_PATH=dev-lib
  - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
  - source $DEV_LIB_PATH/travis.before_script.sh
  - export LIMIT_TRAVIS_PR_CHECK_SCOPE=all
  - export WPCS_GIT_TREE=develop
  - export PATH_INCLUDES='*.* css inc js sass'

script:
  - $DEV_LIB_PATH/travis.script.sh

after_script:
  - $DEV_LIB_PATH/travis.after_script.sh
